### PR TITLE
fixes #101

### LINKED ISSUE #101: History: restore, preview and delete actions not working
### Issue Summary

Preview button displays not found page
Delete returns 'success' => false
Restore sets title and content to 'undefined'

### Steps to Reproduce

1. Create a post and edit it a few times
2. Select post and go to settings -> History
3. Try to restore any revision, or delete or preview

### Additional info

- Leafpub version: dev
- PHP version:7

### PR DESCRIPTION
**Pull request by fedesanchez**
### Pull Request Summary

This fixes bug #101 

### Have you...

- [x ] Checked that your code adheres to our code guidelines?

---

### Contributor License Agreement

We want Leafpub to remain free and open for everyone to use forever, so please don’t submit any code or content that is licensed or copyrighted without first getting written consent.

Before we accept your pull request, we ask that you agree to the following terms to ensure there are no conflicts with Leafpub’s license now or in the future.

1. I certify that the code I am contributing to this project is completely original or free of any known license or copyright.

2. I agree to allow the developer of Leafpub license or relicense my work at their discretion. By submitting this pull request, I agree to forfeit all copyrights, intellectual property rights, and royalties pertaining to my contribution.

3. By entering my name in the space provided below, I agree to all of the terms mentioned above.

Signed: [Federico Augusto Sanchez]

Date: [2017-03-04]

### CODE REVIEW

File: app/source/classes/Models/History.php [hunk 1]
```diff
@@ -56,7 +56,8 @@ public static function getOne($id){
         try {
             $history = self::getModel()->select(['id' => $id])->current();
             if (!$history) return false;
-            return $history->getArrayCopy();
+            $history['post_data']=json_decode($history['post_data'],true);
```
Comment (karsasmus) [inline app/source/classes/Models/History.php]: At the bottom of the model there's a `normalize` - method which normalizes the data.
I've forgotten to call the method.
Would you mind to change your PR to following code?

```php
$revision = self::normalize($history->getArrayCopy());
return $revision;
```

File: app/source/classes/Controller/APIController.php [hunk 2]
```diff
@@ -584,7 +584,7 @@ public function getPlugins($request, $response, $args) {
     public function deleteHistory($request, $response, $args) {
         // Get the history item and the affected post so we can verify privileges
         $history = History::getOne($args['id']);
-        $post = Post::getOne($history['slug']);
+        $post = Post::getOne($history['post_data']['slug']);
```
Comment (karsasmus) [inline app/source/classes/Controller/APIController.php]: We must select a post by its id, because a slug can change.

```php
$post = Post::getOne((int) $history['post']);
```

I've updated `Post::getOne()` to select a post with its slug or its id.
